"""
Tool implementations for car-log-core MCP server.
"""

from . import (
    create_vehicle,
    get_vehicle,
    list_vehicles,
    update_vehicle,
    delete_vehicle,
    create_checkpoint,
    get_checkpoint,
    list_checkpoints,
    update_checkpoint,
    delete_checkpoint,
    detect_gap,
    create_template,
    get_template,
    list_templates,
    update_template,
    delete_template,
    create_trip,
    get_trip,
    list_trips,
    update_trip,
    delete_trip,
    create_trips_batch,
)

__all__ = [
    "create_vehicle",
    "get_vehicle",
    "list_vehicles",
    "update_vehicle",
    "delete_vehicle",
    "create_checkpoint",
    "get_checkpoint",
    "list_checkpoints",
    "update_checkpoint",
    "delete_checkpoint",
    "detect_gap",
    "create_template",
    "get_template",
    "list_templates",
    "update_template",
    "delete_template",
    "create_trip",
    "get_trip",
    "list_trips",
    "update_trip",
    "delete_trip",
    "create_trips_batch",
]
